# permissions for end users to view vips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vip-viewer-role
rules:
- apiGroups:
  - dns.kube-vip.io
  resources:
  - vips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.kube-vip.io
  resources:
  - vips/status
  verbs:
  - get
